apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

commonLabels:
  variant: development

# replace the image tag of the container with latest
images:
- name: quay.io/wpernath/person-service:latest
#  newTag: v1.8.9-native
  newTag: v1.8.9-jvm

# generate a configmap 
configMapGenerator:
- name: app-config
  literals:
  - APP_GREETING=We are in DEVELOPMENT mode
  options:
    disableNameSuffixHash: true

# This patch provides the name of the namespace into the env-value of the Job
# This is needed because we want to call the target rest service of person-service
# which is: person-service.$NAMESPACE.svc:8080
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: book-kn
  target:
    kind: Job

